FILE_SEP = "\t"
INDEX_FILE_SEP = " "

PAD_TOKEN = "<PAD>"
UNK_TOKEN = "<UNK>"
START_TOKEN = "<StartSent>"
END_TOKEN = "<EndSent>"

SPECIAL_TOKENS_INDEX = {PAD_TOKEN: 0, UNK_TOKEN: 1, START_TOKEN: 2, END_TOKEN: 3}